import random

print('Welcome to Secret Santa! Please press "Enter" to continue and have fun!')
#'Laura', 'Luke', 'Peter', 'Alex', 'David', 'Chrissie', 'Emilija', 'Tim', 'Raian'

main = []
choosers = []
partners = []

participants = str(input())
finished = 'done'
while participants != 'done':
    participants = str(input('Please enter the first name of a participant, with the first letter capitalized and press "Enter". Once you are finished, please type "done".'))
    main.append(participants)
    choosers.append(participants)
    partners.append(participants)
else:
    main.remove(participants)
    choosers.remove(participants)
    partners.remove(participants)

for name in main:
    your_name = input('What is your first name? (Please capitalize the first letter.)')
    if your_name in partners:
        partners.remove(your_name)
        chosen_partner = random.choice(partners)
        print('You must buy a gift for', chosen_partner)
        choosers.remove(your_name)
        partners.remove(chosen_partner)
        partners.append(your_name)
        print('NEXT')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print('Please carefully scroll up to see who you must buy a gift for. After you are done, scroll back down for the next person.')
    else:
        chosen_partner = random.choice(partners)
        print('You must buy a gift for', chosen_partner)
        choosers.remove(your_name)
        partners.remove(chosen_partner)
        print('NEXT')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print(' |')
        print('Please carefully scroll up to see who you must buy a gift for. After you are done, scroll back down for the next person.')
print('Finished - happy present-buying :)')
